openweathermap.apikey=2f0140ada1e44bc7580905ddd7cd76ec
openweathermap.apikey.backup=152937b389e31da6be83e10aab07387c
wolframalpha.appid=3L279GYYHE
wolframalpha.appid.backup=XPYYLEK98P
wolframalpha.appid.tertiary=HGGGWHGT74